name: ticketing_app_flutter
description: A Flutter ticketing application with Firebase integration.

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.4
  printing: ^5.12.0

  
  # Firebase dependencies
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  
  # UI and utilities
  cupertino_icons: ^1.0.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/button.png
    - assets/images/i (1).png
    - assets/images/i.png
    - assets/images/landing.png
    - assets/images/svg (1).png
    - assets/images/svg.png
    - assets/images/QR (1).png
    - assets/images/QR.png
    - assets/images/6963703 1.png