// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVf8sPOTHmfOkkwpaSq3XF553EVdkRQA0',
    appId: '1:1016509561963:web:933865c4ce6f9796ebc52e',
    messagingSenderId: '1016509561963',
    projectId: 'ticketing-app-bd080',
    authDomain: 'ticketing-app-bd080.firebaseapp.com',
    storageBucket: 'ticketing-app-bd080.firebasestorage.app',
    measurementId: 'G-5TD0VQPE6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFnUmhk193ioYCypVX5ZPNleUyo8stjUA',
    appId: '1:1016509561963:android:473fa4f6aea769d5ebc52e',
    messagingSenderId: '1016509561963',
    projectId: 'ticketing-app-bd080',
    storageBucket: 'ticketing-app-bd080.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmagaTLM1ch7lnYi-EjpoBC6PvGtyGAaU',
    appId: '1:1016509561963:ios:ac470c8463419ef5ebc52e',
    messagingSenderId: '1016509561963',
    projectId: 'ticketing-app-bd080',
    storageBucket: 'ticketing-app-bd080.firebasestorage.app',
    iosBundleId: 'com.example.ticketingAppFlutter',
  );

}